### ISSUE TITLE
Create a self-hosted version of Eternity

### ISSUE THREAD

**Issue by rickcecil** [jc9108/eternity#2]
Based on our discussion here:
https://github.com/jc9108/eternity/discussions/1

Eternity is currently not setup to be self-hosted. I know I would very much appreciate being able to have a version of this running on my local network. There really isn't anything else out there like this app.

As you noted in the thread, there are a few issues that would need to be worked out. Here is a high-level list of items:

- Documenting secrets keys and necessary values
- Removing some features/items (e.g. elephantsql) that are specific to centralized hosting
- Setup Documentation

Should you decide to do this, I would be happy to help out. While not a developer, I can help with documentation and UX design and maybe some frontend coding, though I would need to learn Node.

Let me know what other details you need for this ticket and I can provide them.

**Comment by jc9108** [comment]
i dont need any help (thx for offer), but making a (good) selfhosted version will involve quite a bit more work than those things you listed. afterwards ill have to maintain 2 different versions of the app at the same time which will be a pain. so like i said in the discussion there needs to be reasonable demand for me to make this. lets say 50 👍 on this issue and ill do it. good luck.

**Comment by laundmo** [comment]
I don't quite see the point with maintaining 2 versions, since its already a web app, shouldn't a selfhostaboe version be quite easy?

**Comment by jc9108** [comment]
btw i didnt expect this to get 50 👍 so quickly lol. i will start on this next month, but it's not super trivial (especially as someone who is still learning these technologies), and i wont be working on this full time, so i dont want to provide a timeline on it right now. feel free to subscribe to this issue to receive a notification when it's done.

**Comment by ZaxLofful** [comment]
> 

As someone who wants to use this self-hosted, I don't see why you couldn't make it exactly the way it is now; just with a "install" script. Which will populate a DB and needed other things.

If I were to use this and self-host it (which I voted for), I would very much like all of the features you mentioned "are unnecessary for a selfhosted instance."

I would be offering it as one of the services for my users (friends and family), whom would benefit greatly from all of those features; like email verification and notifications.

As long as it works with OAuth2/OIDC2 then I would be really happy, because I would integrate it with Authentik (uses Discord OAtuh2 as login source).

**Comment by quaintdev** [comment]
I agree with @jc9108. If I'm going to self host the application I don't want anything with Firebase or any other service. Everything on my local system please!

**Comment by jc9108** [comment]
@ZaxLofful

please read the above. there is a bunch of **manual** setup in various web services required for the current version which (as far as im aware) cannot be done via an install script. initializing a db is not part of that setup i am talking about, and is actually done programatically already.

another reason is that the current version doesnt run completely isolated. there is code connecting the backend websocket as a client to a different server ([also open sourced](https://github.com/jc9108/portals)) on the same machine to receive some extraneous info such as the domain's cloudflare stats.

and the biggest reason by far is that a selfhosted version should use a local database (rather than firebase) for reddit data which provides the benefits i have stated above ("free" unlimited storage, download, connections; as long as your server has the resources), not to mention the other improvements that will be tailored to a selfhosted version.

im pretty sure most selfhosters just want to use it for personal use anyways. in which case the selfhosted version is objectively better.

you only find the email features useful because youre trying to host it for others, which is pretty much not the point of selfhosting lol. even then, you can just run multiple selfhost instances, or if you really want to selfhost the current version, just read through #1 and the `package.json`s in the repo. most/all of the info you need is there. like i said, i literally cannot create a install script for that setup.

all of this has pretty much already been said before either in a previous comment or in #1. please stop making me repeat lol!

**Comment by sugoidogo** [comment]
@ZaxLofful as someone with a basic understanding of the technologies at hand, that's not reasonable. You can't take code designed from the ground up as a centralized service and self host it with a bash script. There's gonna have to be lots of changes just for it to be self hostable, and on top of that the dev is planning on optimizing that version further for self hosting. I agree that features like email verification should stay, but they're gonna need re-implementation to allow the hoster to use an email service of their choice. That's just one example of the many changes that would have to be made for it to be reasonably self hostable.

**Comment by jc9108** [comment]
@sugoidogo @J0n4t4n just curious what you think the emailing is for? currently in the hosted version it is only used to notify a user if there has been an db update failure due to reaching their firebase storage cap, also to notify about account inactivity, where both of these things will not be relevant anymore in a selfhosted version.

as for the authentication, will take that into consideration. thanks

**Comment by laundmo** [comment]
so, to be clear: all this attention and upvotes are coming from a thread on r/selfhosted where this project was posted.

the goal for that subreddit and a lot of it's users isn't to host applications for just themselves. It's about being seperate from big cloud offerings. A lot of people actually do host a bunch of services for other people, family, friends etc, commonly things like password managers, media management, "cloud" storage etc. i think the assumption that most selfhosters don't need multi-user support is just plain wrong.

**Comment by jc9108** [comment]
okay, that's fair. i can leave the high level implementation as it is currently.

but regardless, my main point is that there are significant improvements that can be made on a version specifically designed for selfhosting. also, even having it stay as a multi-user app would still render the email features to be useless on a selfhosted version due to the reasons mentioned in [this comment](https://github.com/jc9108/eternity/issues/2#issuecomment-1122189751). but if you were to selfhost the app as it currently is, that is still something you'd have to manually set up even though it's not needed anymore.

**Comment by jc9108** [comment]
okay, that's fair. to be honest the entire time i was referring to selfhosted i was thinking of doing a personal-use only version. a personal-use only version is gonna have all the advantages of the bullet points [here](https://github.com/jc9108/eternity/issues/2#issuecomment-1121767177). or, i can make it a exact copy of the current multi-user app, except switch out firebase with psql and also minus emails (for the reasons stated [here](https://github.com/jc9108/eternity/issues/2#issuecomment-1122189751)).

so lets have a poll/vote on this comment.
👍 = personal-use only version
👎 = multi-user version

**Comment by dm2912** [comment]
For me...

Upvote Yes: If it can be installed as a basic app with apache reverse proxy

Upvote No: If its docker

**Comment by J0n4t4n** [comment]
@jc9108 
Then I missunderstood what the emails are for, my bad, then they don't seem important.



My ideal setup would:
- be self-hosted
- support a few users at a time
- have its own user accounts or utilize ldap
- allow to connect a Reddit account to a user account and have data sync periodically
- process data using the backend

**Comment by rickcecil** [comment]
The multi-user version would be ideal, really. While I will be the only one using it, I have four Reddit accounts and would like to be able to back them all up on a single instance. If it is a single account setup, then I would (as I understand it now) need to create four separate instances of Eternity to be able to back up all four accounts.

**Comment by rickcecil** [comment]
The multi-user version would be ideal, really. While I will be the only one using it, I have four Reddit accounts and would like to be able to back them all up on a single instance. If it is a single account setup, then I would (as I understand it now) need to create four separate instances of Eternity to be able to back up all four accounts.

PS I knew this thing would fill a huge need within the self-hosting community. Well, I wasn't 100% sure, but I was pretty sure. :) Very glad it has turned out so well!

**Comment by jc9108** [comment]
@rickcecil no, a personal use version would support multiple accounts, but just all your own accounts

> the reddit oauth2 flow / app type, and authentication implementation, will likely be changed to facilitate easier usage and quick account switching without having to login through reddit each time

<br/>

also, there are currently more votes for the multi-user version and i just wanted to note the cost that comes with switching to a local db for users' reddit data while keeping it as a multi-user version.

the reason why the current hosted one is so efficient for multi-users is **specifically** attributed to using firebase to store user reddit data. whenever a user visits the site, they retrieve data from their own firebase db. this means there is very minimal server load on eternity's server, which makes it exponentially scalable for a low hosting cost.

however, in a selfhosted multi-user version, if eternity uses a local db for all users' reddit data, that means each time a user visits the site, that load will be placed on your server instead. so your server resource usage / hosting cost with respect to number of users (or specifically actual user usage) will be linear instead. but i suppose this is how most other multi-user selfhosted apps are as well. just wanted to clarify that there is going to be that difference between the current hosted and selfhosted multi-user version though.

**Comment by Z0pyrus** [comment]
any updates on this?

**Comment by jc9108** [comment]
ive released it at [expanse](https://github.com/jc9108/expanse). already tested it for a day and it was fine, can @rickcecil (or others) try it and see if you run into anything i need to address before i close this ?

**Comment by Z0pyrus** [comment]
I'm installing it rn. Do you need a more advanced ReadMe?

**Comment by jc9108** [comment]
i think i covered everything there as i designed it to be straightforward and easy to use. included a `run.sh` script to simplify further. do you have any suggestions?

**Comment by Z0pyrus** [comment]
Idk if this is that important because I have a really weird setup. I have a raspberry pi 4 (8gb) with Ubuntu 22.04.1 LTS which is also running docker in rootless mode which means I had to edit the `run.sh` file a bit. I removed every `sudo` part and also edited every `docker compose ...` part to `docker-compose ...`. 
Also the expanse_frontend does not start on arm64/arm processors idk why.

During the installation I get these Warinings/Errors:
```
4:53:11 PM [vite-plugin-svelte] /frontend/source/components/navbar.svelte:253:35 A11y: '#' is not a valid href attribute
251:           <div class="dropdown-divider m-0"></div>
252:           {#if show_data_anchors}
253:             <a bind:this={import_anchor} href="#">import data</a>
                                              ^
254:             <div bind:this={import_notice} class="bg-info rounded text-light text-left line_height_1 mb-2 pb-1 d-none">
255:               <p class="mx-1">import data that you downloaded from <a href="https://www.reddit.com/settings/data-request" target="_blank" class="text-dark">Reddit data request</a></p>
4:53:11 PM [vite-plugin-svelte] /frontend/source/components/navbar.svelte:278:35 A11y: '#' is not a valid href attribute
276:             </div>
277:             <div class="dropdown-divider m-0"></div>
278:             <a bind:this={export_anchor} href="#">export data</a>
                                              ^
279:             <a bind:this={dl} class="d-none" download></a>
280:             <div class="dropdown-divider m-0"></div>
4:53:11 PM [vite-plugin-svelte] /frontend/source/components/navbar.svelte:279:6 A11y: <a> element should have an href attribute
277:             <div class="dropdown-divider m-0"></div>
278:             <a bind:this={export_anchor} href="#">export data</a>
279:             <a bind:this={dl} class="d-none" download></a>
                 ^
280:             <div class="dropdown-divider m-0"></div>
281:           {/if}
4:53:11 PM [vite-plugin-svelte] /frontend/source/components/navbar.svelte:279:6 A11y: <a> element should have child content
277:             <div class="dropdown-divider m-0"></div>
278:             <a bind:this={export_anchor} href="#">export data</a>
279:             <a bind:this={dl} class="d-none" download></a>
                 ^
280:             <div class="dropdown-divider m-0"></div>
281:           {/if}
4:53:11 PM [vite-plugin-svelte] /frontend/source/components/navbar.svelte:282:33 A11y: '#' is not a valid href attribute
280:             <div class="dropdown-divider m-0"></div>
281:           {/if}
282:           <a bind:this={purge_anchor} href="#">purge account</a>
                                           ^
283:           <div bind:this={purge_warning} class="bg-danger rounded text-light text-left line_height_1 mb-2 pb-1 d-none">
284:             <p class="mx-1">are you sure you want to purge your expanse account?</p>
'RUN' is not exported by '.svelte-kit/runtime/env/static/public.js'
'RUN' is not exported by '.svelte-kit/runtime/env/static/public.js'
'PORT' is not exported by '.svelte-kit/runtime/env/static/public.js'
```

```
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

```

**Comment by jc9108** [comment]
> also edited every `docker compose ...` part to `docker-compose ...`

you are using the older version which is `docker-compose`. if you install the latest version from https://docs.docker.com/engine/install, you will have `docker compose`

<br/>

> the expanse_frontend does not start on arm64/arm processors idk why. But it does work without it

this is intended, the frontend doesnt need to be running. it is only used at buildtime to generate static files which are then served by the backend at runtime

<br/>

those warnings are also known/intended. functionally doesnt affect the app

and the deprecated messages are for dependencies of dependencies, nothing i can do about it. they arent security issues though, so it's fine

**Comment by Z0pyrus** [comment]
Than everything is working fine!

**Comment by Z0pyrus** [comment]
After some time I've run into an issue where the data is not getting updated anymore: `last updated: 15h ago`. I've imported my Reddit data with csv files which lead to an overall saved count of 4410. Also, my pihole fetched about 3800 requests to oauth.reddit.com.
In the console I got this error while it's trying to update the data:
```
RequestError: Error: ETIMEDOUT
    at new RequestError (/backend/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/backend/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/backend/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/backend/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Timeout.<anonymous> (/backend/node_modules/request/request.js:851:16)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  cause: Error: ETIMEDOUT
      at Timeout.<anonymous> (/backend/node_modules/request/request.js:848:19)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7) {
    code: 'ETIMEDOUT',
    connect: true
  },
  error: Error: ETIMEDOUT
      at Timeout.<anonymous> (/backend/node_modules/request/request.js:848:19)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7) {
    code: 'ETIMEDOUT',
    connect: true
  },
      
  options: {
    gzip: true,
    json: true,
    headers: { 'user-agent': 'web:expanse:v=1.0.0 (hosted by u/myusername)' },
    baseUrl: 'https://oauth.reddit.com',
      
{
      raw_json: 1,
      count: 9999,
      limit: 9007199254740991,
      before: 't3_xazslb'
    },
    auth: { bearer: 'hidden for privacy' },
    resolveWithFullResponse: true,
    timeout: 30000,
    transform: [Function: transform],
    uri: 'user/myusername/upvoted',
    method: 'GET',
    callback: [Function: RP$callback],
    simple: true,
    transform2xxOnly: false
  },
  response: undefined
}
```

**Comment by jc9108** [comment]
hmm ive never run into this while testing. i just tested again with an import of over 20k items and its still as expected

![image](https://user-images.githubusercontent.com/31039318/189533183-ab957f04-975c-4bb9-b865-717d18c63b85.png)

is there anything specific you did before this happened?

ill leave an instance up for now and see if it runs into this

**Comment by jc9108** [comment]
actually @Z0pyrus can you resubmit this as a new issue in the new repo, and i will close this issue for now

**Comment by jc9108** [comment]
moved issue to new repo
