### ISSUE TITLE
Make Eternity zero-trust

### ISSUE THREAD

**Issue by zeroby0** [jc9108/eternity#7]
Thank you so much for running the server and making this service free for everyone <3.

Extrapolating from [this comment on Reddit](https://www.reddit.com/r/TheoryOfReddit/comments/rfo7bt/comment/hsz8qin/?utm_source=reddit&utm_medium=web2x&context=3), your server gets a list of saved posts from Reddit API, and then uploads them to to Firebase. I trust you to not invade the privacy of users, but if your server is ever breached, the hackers would have a bunch of working API tokens for Reddit and Firebase. Which is not great.

If the API keys for Reddit are stored on Firebase, and Functions are used to fetch data from Reddit and save it to Firebase's DB, you'd have a system where the user doesn't have to reveal any API keys at all. And I imagine your server costs would be drastically lower.

I haven't figured out a good way to trigger the functions periodically, but maybe we can [trigger them via HTTP calls](https://firebase.google.com/docs/functions/http-events) from your server. (Firebase experts please chime in)

This would make #2 much easier to implement because your server is doing much less, and maybe even eliminate the need for self-hosting if we find a self-contained way to trigger function calls.

**Comment by jc9108** [comment]
> If the API keys for Reddit are stored on Firebase, and Functions are used to fetch data from Reddit and save it to Firebase's DB, you'd have a system where the user doesn't have to reveal any API keys at all. And I imagine your server costs would be drastically lower.

thanks for the suggestion! but firebase projects on the [free plan](https://firebase.google.com/pricing)—which most users are and will be using—cannot run cloud functions. so that's not really viable.

server cost is not an issue; with the way the hosted version is currently implemented, the app is exponentially scalable at a basically constant low cost.

<br/>

as for the server's security, all ports are unexposed except 22, 80, and 443. the server has password login disabled and can only be logged in from my rsa 4096 ssh key. and the app's db stores all sentitive info (emails, tokens, keys) as encrypted values using a secret, a salt, and an iv. github also alerts me when they detect insecure dependencies, which i patch accordingly depending on the relevance. even so, obviously there can still always be a risk when it comes to web apps. so for those people who want to remove trust from the equation, i would suggest waiting for the selfhosted version.

<br/>

> This would make https://github.com/jc9108/eternity/issues/2 much easier to implement because your server is doing much less, and maybe even eliminate the need for self-hosting if we find a self-contained way to trigger function calls.

#2 isnt difficult to implement, it's just that some things came up so i put it on hold for a bit. and i think the selfhosted version is supposed to be entirely selfhosted, which means firebase and cloud functions are out of the question.
