### ISSUE TITLE
Auto sync not working

### ISSUE THREAD

**Issue by Lucas-224** [jc9108/eternity#8]
After importing my saved data from reddit the option to refresh and add new saved posts does not appear. it was working before so maybe i did something wrong? in the demo video on youtube a popup that says new data available with a refresh button. I do not have this. my last data update was 1m ago. 
cool app btw. 
thanks!

**Comment by jc9108** [comment]
after you use the import feature, the items in the csv files are not immediately imported, it starts importing on the next update cycle and may take up to a day to complete depending on how many items there are. this is specified in the modal after you use the import feature::
![image](https://user-images.githubusercontent.com/31039318/192412356-d663d879-0cb5-4070-8c61-b4dbae7341d8.png)

if you stayed on the page, on the "saved" category, until the next update cycle, then the refresh button should have appeared. if you reload the page, it has the same effect

also, note that the items in eternity are sorted by creation datetime, not datetime of actions taken on items / datetime of import. so you will likely not see them at the top of the list when theyve been imported

anyways, since it has been 9h since you posted this, the import should either be complete or partially complete. you can tell if it's working or not if the number of items in the saved category (shown in the search bar) has gone up by more than the number of additional items youve saved on reddit since you started the import. can you check?

**Comment by jc9108** [comment]
after you use the import feature, the items in the csv files are not immediately imported, it starts importing on the next update cycle and may take up to a day to complete depending on how many items there are. this is specified in the modal after you use the import feature::
![image](https://user-images.githubusercontent.com/31039318/192412356-d663d879-0cb5-4070-8c61-b4dbae7341d8.png)

if you stayed on the page, on the "saved" category, until the next update cycle, then the refresh button should have appeared. if you reload the page, it has the same effect

also, note that the items in eternity are sorted by creation datetime, not datetime of actions taken on items / datetime of import. so you will likely not see them at the top of the list when theyve been imported

anyways, since it has been 9h since you posted this, the import should either be complete or partially complete. you can tell if it's working or not if the number of items in the saved category (shown in the search bar) has gone up by more than the number of additional items youve saved on reddit since you started the import. can you check?
